### ISSUE TITLE
Bug when testing in iOS

### ISSUE THREAD

**Issue by miguel-lorenzo** [alice-biometrics/lume#35]
Platform: iOS

Even though tests failed, only warnings are displayed causing github workflow to continue without failing.
![Captura de pantalla 2020-10-07 a las 15 13 26](https://user-images.githubusercontent.com/59612324/95335533-d1f93000-08af-11eb-8a7a-6751fd5956ae.png)

**Comment by acostapazo** [comment]
It could be related with the command you're executing.

If you are using `xcpretty` you have to take [this](https://github.com/xcpretty/xcpretty/issues/25) into account.

**Comment by acostapazo** [comment]
Indeed, this is an xcpretty problem.

See the following workaround https://github.com/xcpretty/xcpretty/pull/26
